# Generated by Django 4.2.3 on 2023-07-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerNumber', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Customer Number')),
                ('customerName', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('contactLastName', models.CharField(max_length=50, verbose_name='Contact Last Name')),
                ('contactFirstName', models.CharField(max_length=50, verbose_name='Contact First Name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('addressLine1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('addressLine2', models.CharField(default=None, max_length=50, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(default=None, max_length=50, null=True, verbose_name='State')),
                ('postalCode', models.CharField(default=None, max_length=15, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('creditLimit', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Credit Limit')),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('officeCode', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Office Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('addressLine1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('addressLine2', models.CharField(default='', max_length=50, verbose_name='Address Line 2')),
                ('state', models.CharField(default='', max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('postalCode', models.CharField(max_length=15, verbose_name='Postal Code')),
                ('territory', models.CharField(max_length=10, verbose_name='Territory')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOrdered', models.PositiveIntegerField(verbose_name='Quantity Ordered')),
                ('priceEach', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Each')),
                ('orderLineNumber', models.PositiveSmallIntegerField(verbose_name='Order Line Number')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderNumber', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Order Number')),
                ('orderDate', models.DateField(verbose_name='Order Date')),
                ('requiredDate', models.DateField(verbose_name='Required Date')),
                ('shippedDate', models.DateField(default=None, null=True, verbose_name='Shipped Date')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.customers', verbose_name='Customer Number')),
            ],
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('productLine', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Product Line')),
                ('textDescription', models.TextField(default=None, null=True, verbose_name='Text Description')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productCode', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Product Code')),
                ('productName', models.CharField(max_length=70, verbose_name='Product Name')),
                ('productScale', models.CharField(max_length=10, verbose_name='Product Scale')),
                ('productVendor', models.CharField(max_length=50, verbose_name='Product Vendor')),
                ('productDescription', models.TextField(verbose_name='Product Description')),
                ('quantityInStock', models.PositiveSmallIntegerField(verbose_name='Quantity In Stock')),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Price')),
                ('MSRP', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MSRP')),
                ('orderNumber', models.ManyToManyField(through='dashboard.Orderdetails', to='dashboard.orders', verbose_name='Order Number')),
                ('productLine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.productlines', verbose_name='Product Line')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.orders', verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.products', verbose_name='Product Code'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeNumber', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Employee Number')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('jobTitle', models.CharField(max_length=50, verbose_name='Job Title')),
                ('officeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.offices', verbose_name='Office Code')),
                ('reportsTo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.employees', verbose_name='reportsTo')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='salesRepEmployeeNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.employees', verbose_name='Sales Rep Employee Number'),
        ),
    ]
