# Generated by Django 4.2.3 on 2023-07-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('paymentDate', models.DateField(verbose_name='Payment Date')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.customers', verbose_name='Customer Number')),
                ('orderNumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.orders', verbose_name='Order Number')),
            ],
        ),
    ]
