# Generated by Django 4.2.3 on 2023-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
    ]
