# Generated by Django 4.2.3 on 2023-07-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='admin_password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='admin_username',
        ),
    ]
