# Generated by Django 4.2.3 on 2023-07-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_password_admin_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_username',
            new_name='username',
        ),
    ]
